routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//My_home
Route::get('home','Home\HomeController@home')->name('home');
//login_register_logout
Route::post('Auth/Register','Auth\RegisterController@create')->name('register');
Route::post('Auth/Login','Auth\LoginController@login')->name('login');
Route::get('Auth/Logout', 'Auth\LoginController@logout')->name('logout');
//manage tag,catagories,products
Route::group(['prefix'=>'admin','middleware'=>['admin']],function(){
	Route::resource('tags', 'Tags\TagsController');
	Route::resource('categories', 'Categories\CategoriesController');
	Route::resource('products', 'Products\ProductsController');
	Route::resource('slide','Slide\SlideController');
	Route::resource('notify','Notify\NotifyController');
});
//manage products
Route::get('product/{id}', 'Products\ProductsController@show')->name('show_product');

Route::post('comments/{id}','Comments\CommentsController@store')->name('comments');
//information_user
Route::group(['prefix'=>'information','middleware'=>['auth']],function(){
    Route::resource('user','Information\InformationController');
    //history
    Route::get('history','History\HistoryController@index')->name('history');
    //oder
    Route::get('oder','Oder\OderController@index')->name('oder');
});
//use_ajax_edit_cart
Route::post('additem','Cart\CartController@additem');
Route::post('deletecart','Cart\CartController@delete');
Route::post('updatecart','Cart\CartController@update');

//test api_googlemaps
Route::get('test',function(){
	$config = array();
    // $config['center'] = 'New York, USA';
    $config['zoom'] = '18';
	$config['map_height'] = '500px';

	$market = array();
	// $config['scrollwheel'] = false;

	GMaps::initialize($config);

	GMaps::add_marker($market);
    $map = GMaps::create_map();
	return view('test/test')->withMap($map);
});
//get_video_youtube
Route::get('video','Test\TestController@video')->name('video');
//send_ajax_products
Route::get('test1','Test\TestController@test');
Route::get('tuong','Test\TestController@tuong');
//add_item_to_cart
Route::post('additems','Cart\CartController@additems');
//information_shop
Route::get('intro','Information\InformationController@intro')->name('intro');
//test
Route::get('test-apiface',function(){

	return view('test/test1');
});
//check_exist_email_and_user
Route::post('checks','Auth\RegisterController@check')->name('check');
Route::post('checkemail-dk','Auth\RegisterController@checkemail')->name('checkemail');
//search
Route::get('search/tuongbongda','Search\SearchController@tuongbongda')->name('tuongbongda');
Route::get('search/vongtaybongda','Search\SearchController@vongtaybongda')->name('vongtaybongda');
Route::post('search-all/name','Search\SearchController@search_all')->name('search-all');
//confirm oder
Route::post('confirm-oder','Oder\OderController@confirm')->name('confirm-oder');

//test menu dep
Route::get('testmenu',function(){
	return view('test/test_search');
});
//test login facebook
Route::get('/redirect/{social}', 'Social\SocialAuthController@redirect')->name('login_facebook');
Route::get('/callback/{social}', 'Social\SocialAuthController@callback');
Route::get('testlogin',function(){
	return view('test/test_login_facebook');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function products()
    {
        return $this->belongsToMany('App\products');
    }
}

app/Http/Controllers/Tags/TagsController.php
<?php

namespace App\Http\Controllers\Tags;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Tag;
use App\Cart;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        $carts = Auth::User()->carts;
        return view('Tags/index')->withTags($tags)->withCarts($carts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,array(
                'name'=>'required|max:255'
            ));
        $tags = new Tag;
        $tags->name = $request->name;
        $tags->save();

        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag =  Tag::find($id);
        $tags = Tag::all();

        return view('Tags/edit')->withTagedit($tag)->withTags($tags)->with('edit','edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->save();
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();

        return redirect()->route('tags.index');
    }
}

resources/views/Tags/edit.blade.php
@extends('main')
@section('contents')
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <h1>Tags</h1>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <th>{{ $tag->id }}</th>
                        <th><a href="{{ route('tags.show', $tag->id) }}">{{ $tag->name }}</a></th>
                        <th>
                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary btn-sm" style="float: left;"> Edit </a>
                             {!! Form::open(['route'=>['tags.destroy',$tag->id],'method'=>'DELETE']) !!}
                                {{ Form::submit('Delete',['class'=>'btn btn-danger btn-sm']) }}
                            {!! Form::close() !!}
                        </th>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-3 col-md-offset-1 form-spacing-top">
            <div class="well">
                {!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
                <h2>New Tag</h2>
                {{ Form::label('name', 'Name:') }}
                {{ Form::text('name', null, ['class' => 'form-control']) }}

                {{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block btn-h1-spacing']) }}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
        
        {{-- Modal-edit --}}
    <div id="myModal-2" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <!-- Modal content-->
            <div class="modal-content">
            <p style="display: none;" id="edit">{{ $edit }}</p>
                <div class="modal-header ">
                    <span>Edit</span>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                <div class="row">
                        <div class="col-md-12">
                            {{ Form::model($tagedit, ['route' => ['tags.update', $tagedit->id], 'method' => "PUT"]) }}

                            {{ Form::label('name', "Tên:") }}
                            {{ Form::text('name', null, ['class' => 'form-control']) }}

                            {{ Form::submit('Save Changes', ['class' => 'btn btn-success', 'style' => 'margin-top:20px;']) }}

                            {{ Form::close() }}
                           </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- end-modal-edit --}}
</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){
        console.log($('#edit').text().length);
        if($('#edit').text().length>2){
            $("#myModal-2").modal('show');
        }
    });
</script>
@stop

resources/views/Tags/index.blade.php
@extends('main')
@section('contents')
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <h1>Tags</h1>
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <th><a href="{{ route('tags.show', $tag->id) }}">{{ $tag->name }}</a></th>
                        <th>
                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary btn-sm" style="float: left;"> Edit </a>
                             {!! Form::open(['route'=>['tags.destroy',$tag->id],'method'=>'DELETE']) !!}
                                {{ Form::submit('Delete',['class'=>'btn btn-danger btn-sm']) }}
                            {!! Form::close() !!}
                        </th>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-3 col-md-offset-1 form-spacing-top">
            <div class="well">
                {!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
                <h2>New Tag</h2>
                {{ Form::label('name', 'Name:') }}
                {{ Form::text('name', null, ['class' => 'form-control']) }}

                {{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block btn-h1-spacing']) }}
                {!! Form::close() !!}
            </div>
        </div>
	</div>
		
		{{-- Modal-edit --}}
	{{-- 	<div id="myModal-2" class="modal fade" role="dialog">
	    <div class="modal-dialog">
	    <!-- Modal content-->
		    <div class="modal-content">
		    	<div class="modal-header ">
				    <span>Edit</span>
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
		    	</div>
		    	<div class="modal-body">
		      	<div class="row">
					    <div class="col-md-12">
						    {{ Form::model($tag, ['route' => ['tags.update', $tag->id], 'method' => "PUT"]) }}

						    {{ Form::label('name', "Tên:") }}
						    {{ Form::text('name', null, ['class' => 'form-control']) }}

						    {{ Form::submit('Save Changes', ['class' => 'btn btn-success', 'style' => 'margin-top:20px;']) }}

						    {{ Form::close() }}
						   </div>
						</div>
					</div>
		    </div>
	    </div>
	</div> --}}
	{{-- end-modal-edit --}}
</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
	$(document).ready(function(){
		if($('#edit').text().length>2){
			$("#myModal-2").modal('show');
		}
	});
</script>
@stop