routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//My_home
Route::get('home','Home\HomeController@home')->name('home');
//login_register_logout
Route::post('Auth/Register','Auth\RegisterController@create')->name('register');
Route::post('Auth/Login','Auth\LoginController@login')->name('login');
Route::get('Auth/Logout', 'Auth\LoginController@logout')->name('logout');
//manage tag,catagories,products
Route::group(['prefix'=>'admin','middleware'=>['admin']],function(){
	Route::resource('tags', 'Tags\TagsController');
	Route::resource('categories', 'Categories\CategoriesController');
	Route::resource('products', 'Products\ProductsController');
	Route::resource('slide','Slide\SlideController');
	Route::resource('notify','Notify\NotifyController');
});
//manage products
Route::get('product/{id}', 'Products\ProductsController@show')->name('show_product');

Route::post('comments/{id}','Comments\CommentsController@store')->name('comments');
//information_user
Route::group(['prefix'=>'information','middleware'=>['auth']],function(){
    Route::resource('user','Information\InformationController');
    //history
    Route::get('history','History\HistoryController@index')->name('history');
    //oder
    Route::get('oder','Oder\OderController@index')->name('oder');
});
//use_ajax_edit_cart
Route::post('additem','Cart\CartController@additem');
Route::post('deletecart','Cart\CartController@delete');
Route::post('updatecart','Cart\CartController@update');

//test api_googlemaps
Route::get('test',function(){
	$config = array();
    // $config['center'] = 'New York, USA';
    $config['zoom'] = '18';
	$config['map_height'] = '500px';

	$market = array();
	// $config['scrollwheel'] = false;

	GMaps::initialize($config);

	GMaps::add_marker($market);
    $map = GMaps::create_map();
	return view('test/test')->withMap($map);
});
//get_video_youtube
Route::get('video','Test\TestController@video')->name('video');
//send_ajax_products
Route::get('test1','Test\TestController@test');
Route::get('tuong','Test\TestController@tuong');
//add_item_to_cart
Route::post('additems','Cart\CartController@additems');
//information_shop
Route::get('intro','Information\InformationController@intro')->name('intro');
//test
Route::get('test-apiface',function(){

	return view('test/test1');
});
//check_exist_email_and_user
Route::post('checks','Auth\RegisterController@check')->name('check');
Route::post('checkemail-dk','Auth\RegisterController@checkemail')->name('checkemail');
//search
Route::get('search/tuongbongda','Search\SearchController@tuongbongda')->name('tuongbongda');
Route::get('search/vongtaybongda','Search\SearchController@vongtaybongda')->name('vongtaybongda');
Route::post('search-all/name','Search\SearchController@search_all')->name('search-all');
//confirm oder
Route::post('confirm-oder','Oder\OderController@confirm')->name('confirm-oder');

//test menu dep
Route::get('testmenu',function(){
	return view('test/test_search');
});
//test login facebook
Route::get('/redirect/{social}', 'Social\SocialAuthController@redirect')->name('login_facebook');
Route::get('/callback/{social}', 'Social\SocialAuthController@callback');
Route::get('testlogin',function(){
	return view('test/test_login_facebook');
});

app/Notify.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notify extends Model
{
    //
}

app/Http/Controllers/Notify/NotifyController.php
<?php

namespace App\Http\Controllers\Notify;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Cart;
use App\Notify;
use Image;

class NotifyController extends Controller
{
    public function index()
    {
        $notifies= Notify::all();
        $carts = Auth::User()->carts;
        return view('notify/all_notify')->withCarts($carts)->withNotifies($notifies);
    }

    public function create()
    {
        // dd('abc');
        $carts = Auth::User()->carts;
        return view('notify/notify')->withCarts($carts);
    }

    public function store(Request $request)
    {
    	$notify = new Notify;
    	$notify->title = $request->title;
    	$notify->describe = $request->describe;
        if($request->hasFile('image'))
        {
            $image=$request->file('image');
            $filename_main=time().'00'.'.'.$image->getClientOriginalExtension();
            $localtion_main= public_path('image/'.$filename_main);
            Image::make($image)->save($localtion_main);
            $notify->image=$filename_main;      
        }
        $notify->save();
        return redirect()->route('home');
    }

    public function edit($id)
    {
    	$carts = Auth::User()->carts;
        $notify = Notify::find($id);
        return view('notify/edit_notify')->withNotify($notify)->withCarts($carts);
    }

    public function update(Request $request,$id)
    {
    	$notify = Notify::find($id);
    	$notify->title = $request->title;
    	$notify->describe = $request->describe;
        if($request->hasFile('image'))
        {
            $image=$request->file('image');
            $filename_main=time().'00'.'.'.$image->getClientOriginalExtension();
            $localtion_main= public_path('image/'.$filename_main);
            Image::make($image)->save($localtion_main);
            $notify->image=$filename_main;      
        }
        $notify->save();
        return redirect()->route('home');
    }

    public function destroy($id)
    {
        $notify = Notify::find($id);
        $notify->delete();

        return redirect()->route('notify.index');
    }
}

resources/views/notify/all_notify.blade.php
@extends('main')
@section('contents')
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-12">
            <h1>Notifies</h1>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Describe</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($notifies as $notify)
                    <tr>
                        <th><a href="{{ route('notify.show', $notify->id) }}">{{ $notify->title }}</a></th>
                        <th>
                            {!! $notify->describe !!}
                        </th>
                        <th>
                            <a href="{{ route('notify.edit', $notify->id) }}" class="btn btn-primary btn-block" style="float: left;"> Edit </a>
                             {!! Form::open(['route'=>['notify.destroy',$notify->id],'method'=>'DELETE']) !!}
                                {{ Form::submit('Delete',['class'=>'btn btn-danger btn-block']) }}
                            {!! Form::close() !!}
                        </th>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
	</div>
</div>
@stop

resources/views/notify/edit_notify.blade.php
@extends('main')
@section('contents')
@section('stylesheets')
  {!!Html::style('css/select2.min.css')!!}
   <script type="text/javascript" src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
@endsection
  <div style="background: #f5f5f5">
    <div class="container">
    	<div class="row">
        {{-- <div class="col-md-2"></div> --}}
      	<div class="col-md-8 col-md-offset-2">
          <div>
            <h1>Edit New Notify</h1>
          </div>
      		<hr>
          {{-- Create form --}}
      		{!! Form::model($notify,array('route'=>['notify.update', $notify->id],'method' => "PUT",'files' => true)) !!}
            {{-- create title --}}
       			{{ Form::label('title','Title') }}
       			{{ Form::text('title',null,array('class'=>'form-control')) }}
            @if ($errors->has('title'))
              <div class="alert alert-danger">
                <strong>{{ $errors->first('title') }}</strong>
              </div>
            @endif
            {{-- create describe --}}
       			{{ Form::label('describe','Describe') }}
       			{{ Form::textarea('describe',null,array('class'=>'form-control')) }}
            <script type="text/javascript">
              var editor = CKEDITOR.replace('describe',{
               language:'vi',
               filebrowserBrowseUrl :'js/ckfinder/ckfinder.html',
               filebrowserImageBrowseUrl : 'js/ckfinder/ckfinder.html?type=Images',
               filebrowserFlashBrowseUrl : 'js/ckfinder/ckfinder.html?type=Flash',
               filebrowserUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
               filebrowserImageUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
               filebrowserFlashUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
               });
            </script>﻿
            @if ($errors->has('describe'))
              <div class="alert alert-danger">
                <strong>{{ $errors->first('describe') }}</strong>
              </div>
            @endif
            {{-- add image to notify --}}
            {{ Form::label('image','Upload Image Main') }}
            {{ Form::file('image',array('class'=>'newavatar')) }}
              <img src="{{ asset('image/'.$notify->image) }}" style="width: 220px;height: 220px">
              @if ($errors->has('image'))
                <div class="alert alert-danger">
                  <strong>{{ $errors->first('image') }}</strong>
                </div>
              @endif
            {{-- submit --}}
       			{{ Form::submit('Create Notify',array('class'=>'btn btn-success btn-lg btn-block','style'=>'margin-top:10px')) }}
    		  {!! Form::close() !!}
      	</div>
      </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript">
    $(".newavatar").change(function(){
      console.log(this);
      let url = URL.createObjectURL(this.files[0]);
      console.log($(this).parent().find('img'));
      $($(this).parent().find('img')).attr('src', url);
      $($(this).parent().find('img')).width(220);
      $($(this).parent().find('img')).height(220);
    })
  </script>
@endsection

resources/views/notify/notify.blade.php
@extends('main')
@section('contents')
@section('stylesheets')
  {!!Html::style('css/select2.min.css')!!}
   <script type="text/javascript" src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
@endsection
  <div style="background: #f5f5f5">
    <div class="container">
    	<div class="row">
        {{-- <div class="col-md-2"></div> --}}
      	<div class="col-md-8 col-md-offset-2">
          <div>
            <h1>Create New Notify</h1>
            <div>
              <button class="btn btn-primary"><a href="{{ route('notify.index') }}" style="color: white;text-decoration: none;">Edit Notify</a></button>
            </div>
          </div>
      		<hr>
          {{-- Create form --}}
      		{!! Form::open(array('route'=>'notify.store','files' => true)) !!}
            {{-- create title --}}
       			{{ Form::label('title','Title') }}
       			{{ Form::text('title',null,array('class'=>'form-control')) }}
            @if ($errors->has('title'))
              <div class="alert alert-danger">
                <strong>{{ $errors->first('title') }}</strong>
              </div>
            @endif
            {{-- create describe --}}
       			{{ Form::label('describe','Describe') }}
       			{{ Form::textarea('describe',null,array('class'=>'form-control')) }}
            <script type="text/javascript">
              var editor = CKEDITOR.replace('describe',{
               language:'vi',
               filebrowserBrowseUrl :'js/ckfinder/ckfinder.html',
               filebrowserImageBrowseUrl : 'js/ckfinder/ckfinder.html?type=Images',
               filebrowserFlashBrowseUrl : 'js/ckfinder/ckfinder.html?type=Flash',
               filebrowserUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
               filebrowserImageUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
               filebrowserFlashUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
               });
            </script>﻿
            @if ($errors->has('describe'))
              <div class="alert alert-danger">
                <strong>{{ $errors->first('describe') }}</strong>
              </div>
            @endif
            {{-- add image to notify --}}
            {{ Form::label('image','Upload Image Main') }}
            {{ Form::file('image',array('class'=>'newavatar')) }}
              <img alt="">
              @if ($errors->has('image'))
                <div class="alert alert-danger">
                  <strong>{{ $errors->first('image') }}</strong>
                </div>
              @endif
            {{-- submit --}}
       			{{ Form::submit('Create Notify',array('class'=>'btn btn-success btn-lg btn-block','style'=>'margin-top:10px')) }}
    		  {!! Form::close() !!}
      	</div>
      </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript">
    $(".newavatar").change(function(){
      console.log(this);
      let url = URL.createObjectURL(this.files[0]);
      console.log($(this).parent().find('img'));
      $($(this).parent().find('img')).attr('src', url);
      $($(this).parent().find('img')).width(220);
      $($(this).parent().find('img')).height(220);
    })
  </script>
@endsection