routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//My_home
Route::get('home','Home\HomeController@home')->name('home');
//login_register_logout
Route::post('Auth/Register','Auth\RegisterController@create')->name('register');
Route::post('Auth/Login','Auth\LoginController@login')->name('login');
Route::get('Auth/Logout', 'Auth\LoginController@logout')->name('logout');
//manage tag,catagories,products
Route::group(['prefix'=>'admin','middleware'=>['admin']],function(){
	Route::resource('tags', 'Tags\TagsController');
	Route::resource('categories', 'Categories\CategoriesController');
	Route::resource('products', 'Products\ProductsController');
	Route::resource('slide','Slide\SlideController');
	Route::resource('notify','Notify\NotifyController');
});
//manage products
Route::get('product/{id}', 'Products\ProductsController@show')->name('show_product');

Route::post('comments/{id}','Comments\CommentsController@store')->name('comments');
//information_user
Route::group(['prefix'=>'information','middleware'=>['auth']],function(){
    Route::resource('user','Information\InformationController');
    //history
    Route::get('history','History\HistoryController@index')->name('history');
    //oder
    Route::get('oder','Oder\OderController@index')->name('oder');
});
//use_ajax_edit_cart
Route::post('additem','Cart\CartController@additem');
Route::post('deletecart','Cart\CartController@delete');
Route::post('updatecart','Cart\CartController@update');

//test api_googlemaps
Route::get('test',function(){
	$config = array();
    // $config['center'] = 'New York, USA';
    $config['zoom'] = '18';
	$config['map_height'] = '500px';

	$market = array();
	// $config['scrollwheel'] = false;

	GMaps::initialize($config);

	GMaps::add_marker($market);
    $map = GMaps::create_map();
	return view('test/test')->withMap($map);
});
//get_video_youtube
Route::get('video','Test\TestController@video')->name('video');
//send_ajax_products
Route::get('test1','Test\TestController@test');
Route::get('tuong','Test\TestController@tuong');
//add_item_to_cart
Route::post('additems','Cart\CartController@additems');
//information_shop
Route::get('intro','Information\InformationController@intro')->name('intro');
//test
Route::get('test-apiface',function(){

	return view('test/test1');
});
//check_exist_email_and_user
Route::post('checks','Auth\RegisterController@check')->name('check');
Route::post('checkemail-dk','Auth\RegisterController@checkemail')->name('checkemail');
//search
Route::get('search/tuongbongda','Search\SearchController@tuongbongda')->name('tuongbongda');
Route::get('search/vongtaybongda','Search\SearchController@vongtaybongda')->name('vongtaybongda');
Route::post('search-all/name','Search\SearchController@search_all')->name('search-all');
//confirm oder
Route::post('confirm-oder','Oder\OderController@confirm')->name('confirm-oder');

//test menu dep
Route::get('testmenu',function(){
	return view('test/test_search');
});
//test login facebook
Route::get('/redirect/{social}', 'Social\SocialAuthController@redirect')->name('login_facebook');
Route::get('/callback/{social}', 'Social\SocialAuthController@callback');
Route::get('testlogin',function(){
	return view('test/test_login_facebook');
});

app/Http/Controllers/Search/SearchController.php
<?php

namespace App\Http\Controllers\Search;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Cart;
use App\products;
use App\Categories;
use GMaps;
use DB;
use Illuminate\Support\Facades\Auth;

class SearchController extends Controller
{
    public function tuongbongda(){
    	$user = Auth::User();
    	$categories = Categories::all()->where('name','Tượng Bóng Đá');		
		$products = products::all()->where('categories_id',$categories[0]->id);
		$carts = Auth::User()->carts;

		foreach($products as $product){
			if(!is_null($product->Comments))
				{
					$product->votes = (float)$product->Comments->avg('star');
				}
			else
				{
					$product->votes=0;
				}
			$product->save();

			$int = (int) $product->votes;
			$float = $product->votes - $int;
			$danhgia = array();
			for($i=0;$i<$int;$i++){
				$danhgia[$i]=100;
			}
			$danhgia[$int]=(int)($float*100);		
			if($int<4){ 
				for($i=$int+1;$i<5;$i++){
					$danhgia[$i]=0;
				}
			}
			$danh_gia_star = collect($danhgia);
			$product->stars = $danh_gia_star;
			$product->save();
		}

    	return view('search/search')->withCarts($carts)->withUser($user)->withProducts($products)->withTitles('Tượng Bóng Đá');
    }

    public function vongtaybongda(){
    	$user = Auth::User();
    	$categories = Categories::all()->where('name','Vòng Tay Bóng Đá')->first();		
		$products = products::all()->where('categories_id',$categories->id);
		$carts = Auth::User()->carts;

		foreach($products as $product){
			if(!is_null($product->Comments))
				{
					$product->votes = (float)$product->Comments->avg('star');
				}
			else
				{
					$product->votes=0;
				}
			$product->save();

			$int = (int) $product->votes;
			$float = $product->votes - $int;
			$danhgia = array();
			for($i=0;$i<$int;$i++){
				$danhgia[$i]=100;
			}
			$danhgia[$int]=(int)($float*100);		
			if($int<4){ 
				for($i=$int+1;$i<5;$i++){
					$danhgia[$i]=0;
				}
			}
			$danh_gia_star = collect($danhgia);
			$product->stars = $danh_gia_star;
			$product->save();
		}

    	return view('search/search')->withCarts($carts)->withUser($user)->withProducts($products)->withTitles('Vòng Tay Bóng Đá');
    }

    public function search_all(Request $request)
    {
    	$search = $request->name_search;
    	$products = DB::table('products')->where('name','like','%'.$search.'%')->get();
    	$carts = Auth::User()->carts;
    	$products_all = products::all();
    	$test = array();
    	$i=0;
    	foreach($products as $product){
    		$test[$i] = $products_all->where('name', $product->name)->first();
    		$i++;
    	}

    	$results = collect($test);
    	foreach($results as $product){
			if(!is_null($product->Comments))
				{
					$product->votes = (float)$product->Comments->avg('star');
				}
			else
				{
					$product->votes=0;
				}
			$product->save();

			$int = (int) $product->votes;
			$float = $product->votes - $int;
			$danhgia = array();
			for($i=0;$i<$int;$i++){
				$danhgia[$i]=100;
			}
			$danhgia[$int]=(int)($float*100);		
			if($int<4){ 
				for($i=$int+1;$i<5;$i++){
					$danhgia[$i]=0;
				}
			}
			$danh_gia_star = collect($danhgia);
			$product->stars = $danh_gia_star;
			 $product->save();
			// dd($product);
		}

    	return view('search/search')->withCarts($carts)->withProducts($results)->withTitles($search);
    }
}

resources/views/search/search.blade.php
@extends('main')
@section('contents')
<div >
	<div class="container" style="margin-top: 39px">
		<div class="search" style="border-bottom: solid 3px green;">
			<strong style="font-size: 30px">{{ $titles }}</strong>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="sort-bar">
					<span class="sort">Sắp Xếp Theo</span>
					<div>
						<div class="sort fix">
							<select class="form-control form-control-lg">
							  	<option>Giá</option>
							  	<option> < 100000 vnđ</option>
							  	<option> > 100000 vnđ</option>
							</select>
						</div>
						<div style="float: right;">
						    <form class="navbar-form navbar-left" action="/action_page.php" >
							     <div class="form-group">
							        <input type="text" class="form-control" placeholder="Search" id="myInput">
							     </div>
							     <button type="submit" class="btn btn-default">Tìm Kiếm</button>
							</form>	
						</div>						
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row" id="myTable">
			@foreach($products as $product)
				<div class="col-md-3" id="khung">
					<div class="items">
						<div class="image-item">
							<img src="{{ asset('image/'.$product->image_main) }}" alt="" class="size-image avataritem" data-toggle="modal" data-target="#myModal" style="cursor: pointer;">
							<a href="{{ route('products.edit', $product->id) }}" id="edit"><i class="far fa-edit edit"></i></a>
						</div>
						<div class="title-item">
							<p style="cursor: pointer;"><a href="{{ route('products.show', $product->id) }}">{{ $product->name }}</a></p>
						</div>
						<div class="price-item">
							<p style="float: left;">{{ $product->price }} vnđ</p>
								@if( $product->stars[0] ==0)
									<div style="padding-left: 71px;">
										<span style="border-left: solid 1px #000;padding-left: 2px;">Chưa Có Đánh Giá</span>
									</div>
								@else
							    <div style="padding-left: 88px">
						  			<div style="display: flex;" id="star">
										<div class="star-eluvation">
											<span class="tyle" style="width: {{ $product->stars[0] }}%">
												<i class="fas fa-star color"></i>
											</span>
										</div>
										<div class="star-eluvation">
											<span class="tyle" style="width: {{ $product->stars[1] }}%">
												<i class="fas fa-star color"></i>
											</span>
										</div>				
										<div class="star-eluvation">
											<span class="tyle" style="width: {{ $product->stars[2] }}%">
												<i class="fas fa-star color"></i>
											</span>
										</div>
										<div class="star-eluvation">
											<span class="tyle" style="width: {{ $product->stars[3] }}%">
												<i class="fas fa-star color"></i>
											</span>
										</div>
										<div class="star-eluvation">
											<span class="tyle" style="width: {{ $product->stars[4] }}%">
												<i class="fas fa-star color"></i>
											</span>
										</div>
									</div>
							  		<div style="display: flex;position: relative;bottom: 16px;color:yellow;">
										<i class="far fa-star color"></i>
										<i class="far fa-star color"></i>
										<i class="far fa-star color"></i>
										<i class="far fa-star color"></i>
										<i class="far fa-star color"></i>
									</div>
								</div>
							@endif
						</div>
						<div class="giohang">
							<button class="btn btn-primary " style="margin-top: -3px;margin-left: 32px;" id="themhang">Thêm Vào Giỏ Hàng</button>
						</div>
					</div>
				</div>
			@endforeach	
		</div>
	</div>
	<div>
		<ul class="pagination" style="margin-left: 488px;">
		    <li><a href="#" style="background: gainsboro;">1</a></li>
		    <li><a href="#">2</a></li>
		    <li><a href="#">3</a></li>
		    <li><a href="#">4</a></li>
		    <li><a href="#">5</a></li>
		</ul>
	</div>

	<div>
		@include('footer')
	</div>
</div>
    <script>
    	$(document).ready(function(){
    	 	$("#fanpage").click(function(){
		        $("#page").show();
		    });
		 	$(".fanpage_tuong").mouseleave(function(){
		     	$("#page").hide();
		    });
		});
    </script>
    <script src='{{ asset('js/add_to_cart.js') }}' type="text/javascript"></script>
@stop