routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//My_home
Route::get('home','Home\HomeController@home')->name('home');
//login_register_logout
Route::post('Auth/Register','Auth\RegisterController@create')->name('register');
Route::post('Auth/Login','Auth\LoginController@login')->name('login');
Route::get('Auth/Logout', 'Auth\LoginController@logout')->name('logout');
//manage tag,catagories,products
Route::group(['prefix'=>'admin','middleware'=>['admin']],function(){
	Route::resource('tags', 'Tags\TagsController');
	Route::resource('categories', 'Categories\CategoriesController');
	Route::resource('products', 'Products\ProductsController');
	Route::resource('slide','Slide\SlideController');
	Route::resource('notify','Notify\NotifyController');
});
//manage products
Route::get('product/{id}', 'Products\ProductsController@show')->name('show_product');

Route::post('comments/{id}','Comments\CommentsController@store')->name('comments');
//information_user
Route::group(['prefix'=>'information','middleware'=>['auth']],function(){
    Route::resource('user','Information\InformationController');
    //history
    Route::get('history','History\HistoryController@index')->name('history');
    //oder
    Route::get('oder','Oder\OderController@index')->name('oder');
});
//use_ajax_edit_cart
Route::post('additem','Cart\CartController@additem');
Route::post('deletecart','Cart\CartController@delete');
Route::post('updatecart','Cart\CartController@update');

//test api_googlemaps
Route::get('test',function(){
	$config = array();
    // $config['center'] = 'New York, USA';
    $config['zoom'] = '18';
	$config['map_height'] = '500px';

	$market = array();
	// $config['scrollwheel'] = false;

	GMaps::initialize($config);

	GMaps::add_marker($market);
    $map = GMaps::create_map();
	return view('test/test')->withMap($map);
});
//get_video_youtube
Route::get('video','Test\TestController@video')->name('video');
//send_ajax_products
Route::get('test1','Test\TestController@test');
Route::get('tuong','Test\TestController@tuong');
//add_item_to_cart
Route::post('additems','Cart\CartController@additems');
//information_shop
Route::get('intro','Information\InformationController@intro')->name('intro');
//test
Route::get('test-apiface',function(){

	return view('test/test1');
});
//check_exist_email_and_user
Route::post('checks','Auth\RegisterController@check')->name('check');
Route::post('checkemail-dk','Auth\RegisterController@checkemail')->name('checkemail');
//search
Route::get('search/tuongbongda','Search\SearchController@tuongbongda')->name('tuongbongda');
Route::get('search/vongtaybongda','Search\SearchController@vongtaybongda')->name('vongtaybongda');
Route::post('search-all/name','Search\SearchController@search_all')->name('search-all');
//confirm oder
Route::post('confirm-oder','Oder\OderController@confirm')->name('confirm-oder');

//test menu dep
Route::get('testmenu',function(){
	return view('test/test_search');
});
//test login facebook
Route::get('/redirect/{social}', 'Social\SocialAuthController@redirect')->name('login_facebook');
Route::get('/callback/{social}', 'Social\SocialAuthController@callback');
Route::get('testlogin',function(){
	return view('test/test_login_facebook');
});

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    public function categories(){
		return $this->belongsTo('App\Categories');
	}
	public function comments(){
		return $this->hasMany('App\Comments');
	}
    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
    public function carts(){
		return $this->hasMany('App\Cart');
	} 
	public function oders(){
		return $this->hasMany('App\Oder');
	}   
	// public function presentPrice()
 //    {
 //        return asDollars($this->price);
 //    }
 //    public function asDollars($value) {
	//     return '$' . number_format($value, 2);
	// }
}

app/Http/Controllers/Products/ProductsController.php
<?php

namespace App\Http\Controllers\Products;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Products;
use App\Categories;
use App\Comments;
use App\Tag;
use App\User;
use App\Cart;
use Image;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $carts = Auth::User()->carts;
        $Categories = Categories::all();
        $tags = Tag::all();
        return view('products/addproduct')->withCategories($Categories)->withTags($tags)->withCarts($carts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'price' => 'required',
            'mieuta' => 'required',
            'xuatxu' => 'required',
            'image_main' => 'file|required|image',
        ]);
        // dd('abc');
        $product = new Products;
        $id = $request->categories[0];
        $Categories = Categories::find($id);

        $product->name = $request->name;
        $product->price = $request->price;
        $product->mieuta = $request->mieuta;
        $product->xuatxu = $request->xuatxu;

        if($request->hasFile('image_main'))
        {
            $image_main=$request->file('image_main');
            $filename_main=time().'00'.'.'.$image_main->getClientOriginalExtension();
            //dd($filename_main);
            $localtion_main= public_path('image/'.$filename_main);
            Image::make($image_main)->resize(488,491)->save($localtion_main);
            $product->image_main=$filename_main;
        }
        if($request->hasFile('image_sub1'))
        {
            $image_sub1=$request->file('image_sub1');
            $filename_sub1=time().'01'.'.'.$image_sub1->getClientOriginalExtension();
            //dd($filename_sub1,$filename_main);

            //dd($product->image_main);
            $localtion_sub1= public_path('image/'.$filename_sub1);
            Image::make($image_sub1)->resize(488,491)->save($localtion_sub1);
            $product->image_sub1=$filename_sub1;
        }
        if($request->hasFile('image_sub2'))
        {
            $image_sub2=$request->file('image_sub2');
            $filename_sub2=time().'02'.'.'.$image_sub2->getClientOriginalExtension();
            //dd($filename_sub2,$filename_sub1,$filename_main);
            $localtion_sub2= public_path('image/'.$filename_sub2);
            Image::make($image_sub2)->resize(488,491)->save($localtion_sub2);
            $product->image_sub2=$filename_sub2;
        }

        $product->categories()->associate($Categories);
        $product->so_luong_nguoi_mua = '0';

        $product->save();

        $product->tags()->sync($request->tags);
        return redirect()->route('home');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = products::find($id);
        $comments = Comments::all();
        if(Auth::User())
        { 
            $carts = Auth::User()->carts;
        }
        else
        {
            $carts=null;
        }
        $admin = User::find(1);

        if(!is_null($product->Comments))
            {
                $product->votes = (float)$product->Comments->avg('star');
            }
        else
            {
                $product->votes=0;
            }
        $product->save();

        $int = (int) $product->votes;
        $float = $product->votes - $int;
        $danhgia = array();
        for($i=0;$i<$int;$i++){
            $danhgia[$i]=100;
        }
        $danhgia[$int]=(int)($float*100);       
        if($int<4){ 
            for($i=$int+1;$i<5;$i++){
                $danhgia[$i]=0;
            }
        }

        $danh_gia_star = collect($danhgia);
        $product->stars = $danh_gia_star;
        $product->save();
        
        return view('products/items')->withProduct($product)->withComments($comments)->withCarts($carts)->withAdmin($admin);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $carts = Auth::User()->carts;
        $product = products::find($id);     
        $Categories = Categories::all();
        $tags = Tag::all();
        $tags2 = array();
        foreach($tags as $tag){
            $tags2[$tag->id] = $tag->name;
        }
        // dd($carts);
        return view('products/editproduct')->withProduct($product)->withCategories($Categories)->withTags($tags2)->withCarts($carts);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'price' => 'required',
            'mieuta' => 'required',
            'xuatxu' => 'required',
        ]);

        $product = products::find($id);
        // $user = Auth::User();
        
        // $this->authorize("update",$user);
        $idcat = $request->categories[0];
        $Categories = Categories::find($idcat);
        $product->name = $request->name;
        $product->price = $request->price;
        $product->mieuta = $request->mieuta;
        $product->xuatxu = $request->xuatxu;

        if($request->hasFile('image_main'))
        {
            $image_main=$request->file('image_main');
            $filename_main=time().'00'.'.'.$image_main->getClientOriginalExtension();
            //dd($filename_main);
            $localtion_main= public_path('image/'.$filename_main);
            Image::make($image_main)->resize(488,491)->save($localtion_main);
            $product->image_main=$filename_main;
        }
        if($request->hasFile('image_sub1'))
        {
            $image_sub1=$request->file('image_sub1');
            $filename_sub1=time().'01'.'.'.$image_sub1->getClientOriginalExtension();
            //dd($filename_sub1,$filename_main);

            //dd($product->image_main);
            $localtion_sub1= public_path('image/'.$filename_sub1);
            Image::make($image_sub1)->resize(488,491)->save($localtion_sub1);
            $product->image_sub1=$filename_sub1;
        }
        if($request->hasFile('image_sub2'))
        {
            $image_sub2=$request->file('image_sub2');
            $filename_sub2=time().'02'.'.'.$image_sub2->getClientOriginalExtension();
            //dd($filename_sub2,$filename_sub1,$filename_main);
            $localtion_sub2= public_path('image/'.$filename_sub2);
            Image::make($image_sub2)->resize(488,491)->save($localtion_sub2);
            $product->image_sub2=$filename_sub2;
        }
        //dd($product->image_main);
        //dd([$product->image_sub2,$product->image_main,$product->image_sub1]);
        $product->categories()->associate($Categories);
        $product->so_luong_nguoi_mua = '0';

        $product->save();

        if(isset($request->tags)){
            $product->tags()->sync($request->tags);
        }
        else{
            $product->tags()->sync(array());
        }
        return redirect()->route('home');        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = products::find($id);
        $product->tags()->detach();
        $product->delete();

        return redirect()->route('home');
    }
}

resources/views/products/addproduct.blade.php
@extends('main')
@section('contents')
@section('stylesheets')
  {!!Html::style('css/select2.min.css')!!}
  {{-- <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>tinymce.init({ 
      selector:'textarea',
      plugins : 'link code'
    });
   </script> --}}
   <script type="text/javascript" src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
@endsection
<div style="background: #f5f5f5">
<div class="container">
	<div class="row">
    {{-- <div class="col-md-2"></div> --}}
  	<div class="col-md-8 col-md-offset-2">
      <div>
        <h1>Create New Product</h1>
        <div>
          <button class="btn btn-primary"><a href="{{ route('tags.index') }}" style="color: white;text-decoration: none;">Create Tag</a></button>
          <button class="btn btn-primary"><a href="{{ route('categories.index') }}" style="color: white;text-decoration: none;">Create Catalogies</a></button>
        </div>
      </div>
  		
  		<hr>
  		{!! Form::open(array('route'=>'products.store','files' => true)) !!}
   			{{ Form::label('name','Tên Sản Phẩm') }}
   			{{ Form::text('name',null,array('class'=>'form-control')) }}
        @if ($errors->has('name'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('name') }}</strong>
          </div>
        @endif
   			{{ Form::label('price','Giá Sản Phẩm') }}
   			{{ Form::text('price',null,array('class'=>'form-control')) }}
				@if ($errors->has('price'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('price') }}</strong>
          </div>
        @endif
   			{{ Form::label('mieuta','Miêu Tả') }}
   			{{ Form::textarea('mieuta',null,array('class'=>'form-control')) }}
        <script type="text/javascript">
          var editor = CKEDITOR.replace('mieuta',{
           language:'vi',
           filebrowserBrowseUrl :'js/ckfinder/ckfinder.html',
           filebrowserImageBrowseUrl : 'js/ckfinder/ckfinder.html?type=Images',
           filebrowserFlashBrowseUrl : 'js/ckfinder/ckfinder.html?type=Flash',
           filebrowserUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
           filebrowserImageUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
           filebrowserFlashUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
           });
        </script>﻿
        @if ($errors->has('mieuta'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('mieuta') }}</strong>
          </div>
        @endif
   			{{ Form::label('xuatxu','Xuất Xứ Sản Phẩm') }}
   			{{ Form::text('xuatxu',null,array('class'=>'form-control')) }}
        @if ($errors->has('xuatxu'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('xuatxu') }}</strong>
          </div>
        @endif
        {{ Form::label('categories', 'Categories:') }}
        <select class="form-control" name="categories[]">
            @foreach($categories as $categori)
            	<option value="{{ $categori->id }}">{{ $categori->name }}</option>
            @endforeach
        </select>
        
        {{ Form::label('tags', 'Tags:') }}
        <select class="form-control select2-multi" name="tags[]" multiple="multiple">
            @foreach($tags as $tag)
              <option value="{{ $tag->id }}">{{ $tag->name }}</option>
            @endforeach
        </select>
        <div style="display: flex;">
          <div>
            {{ Form::label('image_main','Upload Image Main') }}
            {{ Form::file('image_main',array('class'=>'newavatar')) }}
            <img alt="">
            @if ($errors->has('image_main'))
            <div class="alert alert-danger">
              <strong>{{ $errors->first('image_main') }}</strong>
            </div>
            @endif
          </div>
            
          <div>
            {{ Form::label('image_sub1','Upload Image Sub 1') }}
            {{ Form::file('image_sub1',array('class'=>'newavatar')) }}
            <img alt="">
          </div>

          <div>
            {{ Form::label('image_sub2','Upload Image Sub 2') }}
            {{ Form::file('image_sub2',array('class'=>'newavatar')) }}
            <img alt="">
          </div>
        </div>
        <br>
   			{{ Form::submit('Create Post',array('class'=>'btn btn-success btn-lg btn-block')) }}
		  {!! Form::close() !!}
  	</div>
  </div>
</div>
</div>

@section('scripts')
    {!! Html::script('js/select2.min.js') !!}

    <script type="text/javascript">
        $('.select2-multi').select2();
    </script>

@endsection
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      $(".newavatar").change(function(){
        console.log(this);
        let url = URL.createObjectURL(this.files[0]);
        console.log($(this).parent().find('img'));
        $($(this).parent().find('img')).attr('src', url);
        $($(this).parent().find('img')).width(220);
        $($(this).parent().find('img')).height(220);
      })
    </script>
@stop

resources/views/products/editproduct.blade.php
@extends('main')
@section('contents')

@section('stylesheets')
    {!!Html::style('css/select2.min.css')!!}
    {{-- <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({ 
        selector:'textarea',
        plugins : 'link code'
      });
   </script> --}}
   <script type="text/javascript" src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
@endsection
<div style="background: #f5f5f5">
<div class="container">
	<div class="row">
    {{-- <div class="col-md-2"></div> --}}
  	<div class="col-md-8 col-md-offset-2">
  		<h1 style="float: left;">Edit Product</h1>
      <div style="position: relative;left: 485px;top: 19px;">
        {!! Form::open(['route'=>['products.destroy',$product->id],'method'=>'DELETE']) !!}
          {{ Form::submit('Delete',['class'=>'btn btn-danger btn-sm']) }}
        {!! Form::close() !!}
      </div>
  		<hr>
  		{{ Form::model($product, ['route' => ['products.update', $product->id], 'method' => "PUT",'files' => true]) }}
   			{{ Form::label('name','Tên Sản Phẩm') }}
   			{{ Form::text('name',null,array('class'=>'form-control')) }}
        @if ($errors->has('name'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('name') }}</strong>
          </div>
        @endif
   			{{ Form::label('price','Giá Sản Phẩm') }}
   			{{ Form::text('price',null,array('class'=>'form-control')) }}
				@if ($errors->has('price'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('price') }}</strong>
          </div>
        @endif
   			{{ Form::label('mieuta','Miêu Tả') }}
   			{{ Form::textarea('mieuta',null,array('class'=>'form-control')) }}
        <script type="text/javascript">
          var editor = CKEDITOR.replace('mieuta',{
           language:'vi',
           filebrowserBrowseUrl :'js/ckfinder/ckfinder.html',
           filebrowserImageBrowseUrl : 'js/ckfinder/ckfinder.html?type=Images',
           filebrowserFlashBrowseUrl : 'js/ckfinder/ckfinder.html?type=Flash',
           filebrowserUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
           filebrowserImageUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
           filebrowserFlashUploadUrl : 'js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
           });
        </script>﻿
        @if ($errors->has('mieuta'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('mieuta') }}</strong>
          </div>
        @endif
   			{{ Form::label('xuatxu','Xuất Xứ Sản Phẩm') }}
   			{{ Form::text('xuatxu',null,array('class'=>'form-control')) }}
        @if ($errors->has('xuatxu'))
          <div class="alert alert-danger">
            <strong>{{ $errors->first('xuatxu') }}</strong>
          </div>
        @endif

        {{ Form::label('categories', 'Categories:') }}
        <select class="form-control" name="categories[]">
            @foreach($categories as $categori)
            	<option value="{{ $categori->id }}">{{ $categori->name }}</option>
            @endforeach
        </select>
        
        <div style="display: flex;">
          <div>
            {{ Form::label('image_main','Upload Image Main') }}
            {{ Form::file('image_main',array('class'=>'newavatar')) }}
            <img src="{{ asset('image/'.$product->image_main) }}" style="height: 220px;width: 220px;">
            @if ($errors->has('image_main'))
            <div class="alert alert-danger">
              <strong>{{ $errors->first('image_main') }}</strong>
            </div>
            @endif
          </div>
            
          <div>
            {{ Form::label('image_sub1','Upload Image Sub 1') }}
            {{ Form::file('image_sub1',array('class'=>'newavatar')) }}
            <img src="{{ asset('image/'.$product->image_sub1) }}" style="height: 220px;width: 220px;">
          </div>

          <div>
            {{ Form::label('image_sub2','Upload Image Sub 2') }}
            {{ Form::file('image_sub2',array('class'=>'newavatar')) }}
            <img src="{{ asset('image/'.$product->image_sub2) }}" style="height: 220px;width: 220px;">
          </div>
        </div>
        <br>
   			{{ Form::submit('Edit Product',array('class'=>'btn btn-success btn-lg btn-block')) }}
		  {!! Form::close() !!}
  	</div>
  </div>
</div>
</div>

@section('scripts')

  {!! Html::script('js/select2.min.js') !!}

  <script type="text/javascript">
      $('.select2-multi').select2();
      $('.select2-multi').select2().val({!!$product->tags()->allRelatedIds() !!}).trigger('change');
  </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      $(".newavatar").change(function(){
        console.log(this);
        let url = URL.createObjectURL(this.files[0]);
        console.log($(this).parent().find('img'));
        $($(this).parent().find('img')).attr('src', url);
        $($(this).parent().find('img')).width(220);
        $($(this).parent().find('img')).height(220);
      })
    </script>
@endsection
@stop

resources/views/products/productspage.blade.php
@foreach($products as $product)
	<div class="col-md-3" id="khung">
		<div class="items">
			<div class="image-item">
				<img src="{{ asset('image/'.$product->image_main) }}" alt="" class="size-image avataritem" data-toggle="modal" data-target="#myModal" style="cursor: pointer;">
				@if(Auth::check())
				 	@if(Auth::User()->can('update',$product))
						<a href="{{ route('products.edit', $product->id) }}" id="edit"><i class="far fa-edit edit"></i></a>
					@endif
				@endif
			</div>
			<div class="title-item">
				<p style="cursor: pointer;"><a href="{{ route('show_product', $product->id) }}">{{ $product->name }}</a></p>
			</div>
			<div class="price-item">
				<p style="float: left;">{{ $product->price/1000 }}.000 vnđ</p>
					@if( $product->stars[0] ==0)
						<div style="padding-left: 71px;">
							<span style="border-left: solid 1px #000;padding-left: 2px;">Chưa Có Đánh Giá</span>
						</div>
					@else
				    <div style="padding-left: 88px">
			  			<div style="display: flex;" id="star">
							<div class="star-eluvation">
								<span class="tyle" style="width: {{ $product->stars[0] }}%">
									<i class="fas fa-star color"></i>
								</span>
							</div>
							<div class="star-eluvation">
								<span class="tyle" style="width: {{ $product->stars[1] }}%">
									<i class="fas fa-star color"></i>
								</span>
							</div>				
							<div class="star-eluvation">
								<span class="tyle" style="width: {{ $product->stars[2] }}%">
									<i class="fas fa-star color"></i>
								</span>
							</div>
							<div class="star-eluvation">
								<span class="tyle" style="width: {{ $product->stars[3] }}%">
									<i class="fas fa-star color"></i>
								</span>
							</div>
							<div class="star-eluvation">
								<span class="tyle" style="width: {{ $product->stars[4] }}%">
									<i class="fas fa-star color"></i>
								</span>
							</div>
						</div>
				  		<div style="display: flex;position: relative;bottom: 16px;color:yellow;">
							<i class="far fa-star color"></i>
							<i class="far fa-star color"></i>
							<i class="far fa-star color"></i>
							<i class="far fa-star color"></i>
							<i class="far fa-star color"></i>
						</div>
					</div>
				@endif
			</div>
			<div class="giohang">
				<button class="btn btn-primary " style="margin-top: -3px;margin-left: 32px;" id="themhang">Thêm Vào Giỏ Hàng</button>
			</div>
		</div>
	</div>
@endforeach	